/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eos.gui;

import eos.io.*;

import java.awt.TextArea;
import java.util.*;
import javax.swing.JOptionPane;

/**
 *
 * @author M. Dommert
 */
public class eosGUI extends javax.swing.JFrame {
    
    public static final String VERSION_NUMBER = "1.0.1";
    
    private String line;
    private String header;
    private int numberOfSpheres;
    private int numberOfEnergyBins;
    private double dataCorrectionFactor;
    private List<String> sphereNames = new ArrayList<String>();
    private List<Double> sphereDiameter = new ArrayList<Double>();
    private List<Double> sphereCounts = new ArrayList<Double>();
    private List<Double> sphereAbsUncertainty = new ArrayList<Double>();
    private List<Double> spherePerUncertainty = new ArrayList<Double>();
    private List<Double> responsePerUncertainty = new ArrayList<Double>();
    
    private int errorFlag = 0;
    CheckUserInput checkInput = new CheckUserInput();
    
    /**
     * Creates new form ihtGUI
     */
    public eosGUI() {
        initComponents();
        // write welcome message to LogOut
        appendingTextOutLog.appendTextMajor("Welcome to Eos v" 
                                            + VERSION_NUMBER + "\n");
        appendingTextOutLog.appendText("#==============================#\n");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu2 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        checkboxUMGOut = new java.awt.Checkbox();
        checkboxWinBUGSOut = new java.awt.Checkbox();
        saveButton = new java.awt.Button();
        checkboxStandardOut = new java.awt.Checkbox();
        clearAllButton = new java.awt.Button();
        textFieldOutputName = new java.awt.TextField();
        label10 = new java.awt.Label();
        clearReadUncButton = new java.awt.Button();
        jPanel2 = new javax.swing.JPanel();
        textFieldNumberOfSpheres = new java.awt.TextField();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        textFieldHeader = new java.awt.TextField();
        textAreaDetectorName = new java.awt.TextArea("", 0 , 0 , TextArea.SCROLLBARS_NONE);
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        label5 = new java.awt.Label();
        label6 = new java.awt.Label();
        label7 = new java.awt.Label();
        textFieldDataCorrectionFactor = new java.awt.TextField();
        textAreaDiameter = new java.awt.TextArea("", 0 , 0 , TextArea.SCROLLBARS_NONE);
        textAreaDetectorReading = new java.awt.TextArea("", 0 , 0 , TextArea.SCROLLBARS_NONE);
        textAreaAbsUncertainty = new java.awt.TextArea("", 0 , 0 , TextArea.SCROLLBARS_NONE);
        textAreaPerUncertainty = new java.awt.TextArea("",0,0,TextArea.SCROLLBARS_NONE);
        label8 = new java.awt.Label();
        textAreaResponseUncertainty = new java.awt.TextArea("",0,0,TextArea.SCROLLBARS_NONE);
        label9 = new java.awt.Label();
        button1 = new java.awt.Button();
        button2 = new java.awt.Button();
        addZeroButton = new java.awt.Button();
        labelNEB = new java.awt.Label();
        textFieldEnergyBins = new java.awt.TextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuDefaultSpectrum = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuHelp = new javax.swing.JMenu();
        jMenuItemAbout = new javax.swing.JMenuItem();

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Eos: Version " + VERSION_NUMBER);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "OUTPUT"));

        checkboxUMGOut.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        checkboxUMGOut.setLabel("UMG Output");
        checkboxUMGOut.setState(true);

        checkboxWinBUGSOut.setLabel("WinBUGS Output");
        checkboxWinBUGSOut.setState(true);

        saveButton.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        saveButton.setLabel("Create Output");
        saveButton.setName("saveButton"); // NOI18N
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveOutputActionPerformed(evt);
            }
        });

        checkboxStandardOut.setEnabled(false);
        checkboxStandardOut.setLabel("Standard Output");
        checkboxStandardOut.setState(true);

        clearAllButton.setLabel("Clear All TextArea");
        clearAllButton.setName("clearAllButton"); // NOI18N
        clearAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearAllButtonActionPerformed(evt);
            }
        });

        textFieldOutputName.setText("default");

        label10.setText("Output Name:");

        clearReadUncButton.setLabel("Clear Read./Unc.");
        clearReadUncButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearReadUncButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(textFieldOutputName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(checkboxUMGOut, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkboxWinBUGSOut, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkboxStandardOut, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(clearAllButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clearReadUncButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(checkboxUMGOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkboxWinBUGSOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkboxStandardOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(textFieldOutputName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clearReadUncButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clearAllButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "INPUT"));

        label1.setText("# of Spheres:");

        label2.setText("File Header:");

        textFieldHeader.setName("jTextFieldHeader"); // NOI18N
        textFieldHeader.setText("!header restricted to max. 80 characters!");

        textAreaDetectorName.setText("max. 8 char.");

        label3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label3.setName(""); // NOI18N
        label3.setText("Detector");

        label4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label4.setText("Diameter");

        label5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label5.setText("Detector Reading M");

        label6.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label6.setText("abs. uncertainty of M");

        label7.setText("Data Correctrion Factor:");

        textFieldDataCorrectionFactor.setText("0.0");

        textAreaDiameter.setText("00.0");

        textAreaDetectorReading.setPreferredSize(new java.awt.Dimension(100, 300));
        textAreaDetectorReading.setText("0.0000E+00\n" + "or\n" + "0.0000");

        textAreaAbsUncertainty.setPreferredSize(new java.awt.Dimension(100, 300));
        textAreaAbsUncertainty.setText("0.0000E+00\n" + "or\n" + "0.0000");

        textAreaPerUncertainty.setName(""); // NOI18N
        textAreaPerUncertainty.setPreferredSize(new java.awt.Dimension(100, 300));
        textAreaPerUncertainty.setText("0.00");

        label8.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label8.setText("% uncertainty of M");

        textAreaResponseUncertainty.setPreferredSize(new java.awt.Dimension(100, 300));
        textAreaResponseUncertainty.setText("0.0");

        label9.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label9.setText("% uncertainty of R");

        button1.setEnabled(false);
        button1.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        button1.setLabel("calc. from %unc.");

        button2.setEnabled(false);
        button2.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        button2.setLabel("calc. from abs.unc.");

        addZeroButton.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        addZeroButton.setLabel("add 0.0");
        addZeroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addZeroButtonActionPerformed(evt);
            }
        });

        labelNEB.setText("# of Energy Bins:");

        textFieldEnergyBins.setText("131");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textAreaDetectorName, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textAreaDiameter, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(label5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textAreaDetectorReading, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(button1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(textAreaAbsUncertainty, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(label8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(textAreaPerUncertainty, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textAreaResponseUncertainty, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addZeroButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textFieldHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(textFieldNumberOfSpheres, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFieldDataCorrectionFactor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelNEB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFieldEnergyBins, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textFieldNumberOfSpheres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldDataCorrectionFactor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNEB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldEnergyBins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(label5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(label4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(label6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(label3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textAreaResponseUncertainty, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textAreaDiameter, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textAreaDetectorName, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textAreaDetectorReading, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textAreaAbsUncertainty, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textAreaPerUncertainty, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(button1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addZeroButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "PROCESS LOG"));

        appendingTextOutLog.setContentType("text/html"); // NOI18N
        appendingTextOutLog.setText("");
        jScrollPane1.setViewportView(appendingTextOutLog);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        jMenu1.setText("File");

        jMenuItem1.setText("Load UMG File");
        jMenuItem1.setEnabled(false);
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Load WinBUGS File");
        jMenuItem2.setEnabled(false);
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenuDefaultSpectrum.setText("Default Spectrum");

        jMenuItem3.setText("Create Default Spectrum");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenuDefaultSpectrum.add(jMenuItem3);

        jMenuBar1.add(jMenuDefaultSpectrum);

        jMenuHelp.setText("Help");

        jMenuItemAbout.setText("About");
        jMenuItemAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAboutActionPerformed(evt);
            }
        });
        jMenuHelp.add(jMenuItemAbout);

        jMenuBar1.add(jMenuHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SaveOutputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveOutputActionPerformed
        //============START: Read data from GUI=================================
        header = textFieldHeader.getText();
        try {
            numberOfSpheres = Integer.parseInt(textFieldNumberOfSpheres.getText());
        } catch (NumberFormatException e1) {
            errorFlag = 1;
            appendingTextOutLog.appendTextErrorMinor("# of spheres: "
                                                + "requires integer value!\n");
        }    
        try {
            numberOfEnergyBins = Integer.parseInt(textFieldEnergyBins.getText());
        } catch (NumberFormatException e2) {
            errorFlag = 1;
            appendingTextOutLog.appendTextErrorMinor("# of E bins: "
                                                + "requires integer value!\n");
        }   
        try {
            dataCorrectionFactor = Double.parseDouble(textFieldDataCorrectionFactor.getText());
        } catch (NumberFormatException e3) {
            errorFlag = 1;
            appendingTextOutLog.appendTextErrorMinor("Data corr. factor: "
                                                + "requires double value!\n");
        }   
        
        try {
        for (String line : textAreaDetectorName.getText().split("\\n")) {
            line = line.replaceAll("\\s+","");                                  // remove space and hidden blank characters
            if(line.length()>8){              
                sphereNames.add(line.substring(0,8));                           // Format restriction: DetectorName is only valid with max. 8 characters
            } else {
                sphereNames.add(line);
            }
        }
        for (String line : textAreaDiameter.getText().split("\\n")) {
        sphereDiameter.add(Double.parseDouble(line));
        }
        for (String line : textAreaDetectorReading.getText().split("\\n")) {
            sphereCounts.add(Double.parseDouble(line));
        }
        for (String line : textAreaAbsUncertainty.getText().split("\\n")) {
            sphereAbsUncertainty.add(Double.parseDouble(line));
        }
        for (String line : textAreaPerUncertainty.getText().split("\\n")) {
            spherePerUncertainty.add(Double.parseDouble(line));
        }
        for (String line : textAreaResponseUncertainty.getText().split("\\n")) {
            responsePerUncertainty.add(Double.parseDouble(line));
        }
        } catch (NumberFormatException e4) {
            errorFlag = 1;
            appendingTextOutLog.appendTextErrorMinor("Data array contains "
                                                + "invalid data format! \n");
        }
        
        // check, whether length of data array equals number of spheres
        if(checkInput.checkDataUniformity(numberOfSpheres, sphereNames.size())
          +checkInput.checkDataUniformity(numberOfSpheres, sphereDiameter.size())
          +checkInput.checkDataUniformity(numberOfSpheres, sphereCounts.size())
          +checkInput.checkDataUniformity(numberOfSpheres, sphereAbsUncertainty.size())
          +checkInput.checkDataUniformity(numberOfSpheres, spherePerUncertainty.size())
          +checkInput.checkDataUniformity(numberOfSpheres, responsePerUncertainty.size()) 
           != 0) {
            appendingTextOutLog.appendTextErrorMinor("Data array length inconsistent "
                                                + "with number of spheres! \n");
            errorFlag = 1;
        }
        //============END: Read data from GUI===================================
        
        
        if(errorFlag != 0) {
            appendingTextOutLog.appendTextErrorMajor("Input error. "
                                        + "Please check all input fields! \n");
            errorFlag = 0;
        } else {
        // CHECK: UMG Output requested?
        if(checkboxUMGOut.getState()) {     
            //============START: Write data to file=============================            
            try{
                WriteInputFile writeUMGfile = new WriteInputFile();
                writeUMGfile.writeUMG(textFieldOutputName,
                                header, numberOfSpheres, dataCorrectionFactor,
                                sphereNames, sphereDiameter, sphereCounts,
                                sphereAbsUncertainty, spherePerUncertainty,
                                responsePerUncertainty);
            } catch (Exception e) {
                System.out.println("problem with path : "+ textFieldOutputName.getText());
                System.out.println(e.getMessage());
            }
            //============END: Write data to file===============================
            appendingTextOutLog.appendTextSuccess("Success! UMG file successfully written"
                    + " to: " +  textFieldOutputName.getText() +".ibu \n");
        }  
        
        // CHECK: WinBUGS Output requested?
        if(checkboxWinBUGSOut.getState()) {
            //============START: Write data to file=============================
            try{
                WriteInputFile writeWINfile = new WriteInputFile();
                writeWINfile.writeWinBUGS(textFieldOutputName,
                                    header, numberOfEnergyBins, numberOfSpheres, 
                                    sphereCounts, spherePerUncertainty);
            } catch (Exception e) {
                System.out.println("problem with path : "+ textFieldOutputName.getText());
                System.out.println(e.getMessage());
            }
            //============END: Write data to file===============================
            appendingTextOutLog.appendTextSuccess("WinBUGS file successfully written to: " +  textFieldOutputName.getText() +".txt \n");
        }
        appendingTextOutLog.appendText("#==============================#\n");
        }
        
        //=============START: Information Messages==============================
        if(checkboxWinBUGSOut.getState() == false && checkboxUMGOut.getState() == false) {
            JOptionPane.showMessageDialog(null, "No output format selected!", "Information", JOptionPane.INFORMATION_MESSAGE);         
        }
        if(numberOfSpheres == 0) {
            JOptionPane.showMessageDialog(null, "Number of Spheres equals zero or empty!\n" 
                    + "No data written to file.", "Information", JOptionPane.INFORMATION_MESSAGE);         
        }
        if(header.length() > 80) {
            JOptionPane.showMessageDialog(null, "Header length greater 80 characters.\n" 
                    + "Header shortened to max. 80 characters.", "Information", JOptionPane.INFORMATION_MESSAGE);         
        }
        //=============END: Information Messages================================
        
        //============START: clear ArrayLists===================================
        // free ArrayList, so there is no build-up due to multiple use of SaveOutputActionPerformed
        sphereNames = new ArrayList<String>();
        sphereDiameter = new ArrayList<Double>();
        sphereCounts = new ArrayList<Double>();
        sphereAbsUncertainty = new ArrayList<Double>();
        spherePerUncertainty = new ArrayList<Double>();
        responsePerUncertainty = new ArrayList<Double>();
        //============END: clear ArrayLists=====================================
    }//GEN-LAST:event_SaveOutputActionPerformed

    private void clearAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearAllButtonActionPerformed
        //START: clear text from all TextAreas
        textAreaDetectorName.setText(null);
        textAreaDiameter.setText(null);
        textAreaDetectorReading.setText(null);
        textAreaAbsUncertainty.setText(null);
        textAreaPerUncertainty.setText(null);
        textAreaResponseUncertainty.setText(null);
        //END: clear text from all TextAreas
    }//GEN-LAST:event_clearAllButtonActionPerformed

    private void addZeroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addZeroButtonActionPerformed
        try {
            numberOfSpheres = Integer.parseInt(textFieldNumberOfSpheres.getText());
        } catch (NumberFormatException e) {
        // Invalid double String.
        }
        textAreaResponseUncertainty.setText(null);
        for(int i = 0; i < numberOfSpheres; i ++ ) {
            textAreaResponseUncertainty.append("0.0\n");
        }
    }//GEN-LAST:event_addZeroButtonActionPerformed

    private void clearReadUncButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearReadUncButtonActionPerformed
        //START: clear text from Reading and Unc.
        textAreaDetectorReading.setText(null);
        textAreaAbsUncertainty.setText(null);
        textAreaPerUncertainty.setText(null);
        textAreaResponseUncertainty.setText(null);
        //END: clear text from Reading and Unc.
    }//GEN-LAST:event_clearReadUncButtonActionPerformed

    private void jMenuItemAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAboutActionPerformed
        JOptionPane.showMessageDialog(null, "Eos - Version: " + VERSION_NUMBER, "About", JOptionPane.INFORMATION_MESSAGE); 
    }//GEN-LAST:event_jMenuItemAboutActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        defaultSpectrumGUI gui = new defaultSpectrumGUI(eosGUI.this);
        gui.setDefaultCloseOperation(javax.swing.JFrame.HIDE_ON_CLOSE);
        gui.setTitle("Default Spectrum Creator");
        gui.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
                /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new eosGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button addZeroButton;
    private final eos.io.AppendingTextPane appendingTextOutLog = new eos.io.AppendingTextPane();
    private java.awt.Button button1;
    private java.awt.Button button2;
    private java.awt.Checkbox checkboxStandardOut;
    private java.awt.Checkbox checkboxUMGOut;
    private java.awt.Checkbox checkboxWinBUGSOut;
    private java.awt.Button clearAllButton;
    private java.awt.Button clearReadUncButton;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuDefaultSpectrum;
    private javax.swing.JMenu jMenuHelp;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItemAbout;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label label1;
    private java.awt.Label label10;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Label label8;
    private java.awt.Label label9;
    private java.awt.Label labelNEB;
    private java.awt.Button saveButton;
    private java.awt.TextArea textAreaAbsUncertainty;
    private java.awt.TextArea textAreaDetectorName;
    private java.awt.TextArea textAreaDetectorReading;
    private java.awt.TextArea textAreaDiameter;
    private java.awt.TextArea textAreaPerUncertainty;
    private java.awt.TextArea textAreaResponseUncertainty;
    private java.awt.TextField textFieldDataCorrectionFactor;
    private java.awt.TextField textFieldEnergyBins;
    private java.awt.TextField textFieldHeader;
    private java.awt.TextField textFieldNumberOfSpheres;
    private java.awt.TextField textFieldOutputName;
    // End of variables declaration//GEN-END:variables
}
